updates to gha

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -7,24 +7,39 @@ on:
     branches: [main]
 
 jobs:
-  check-version:
-    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/v')
+  get-current-version:
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
-    - name: Package application
-      id: package
-      uses: ./.github/actions/package-app
-      with:
-        app-name: parity_scripter
-        entrypoint: main
-        python-version: "3.9"
     - name: Check app version
-      uses: ./.github/actions/check-version
+      id: current-version
+      uses: ./.github/actions/get-version
       with:
-        app: ${{ steps.package.outputs.app }}
-        ref_name: ${{ github.head_ref }}
+        file: src/parity_scripter/about.py
+
+  check-version:
+    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/v')
+    runs-on: ubuntu-latest
+    needs: [get-current-version]
+
+    steps:
+    - uses: actions/checkout@v4
+    - name: Get expected version
+      id: expected-version
+      shell: bash -el {0}
+      run: |
+        version=$(echo "${{ github.head_ref }}" | sed -e 's+release/v++g')
+        echo "version=$version" >> $GITHUB_OUTPUT
+    - name: Check version
+      shell: bash -el {0}
+      run: |
+        expect_version=${{ steps.expected-version.outputs.version }}
+        got_version=${{ needs.get-current-version.outputs.version }}
+        if [ "$got_version" != "$expect_version" ]; then
+          echo "Error: Version mismatch, update the app version. Expected $expect_version but found $got_version."
+          exit 1
+        fi
 
   app-build:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
@@ -51,8 +66,8 @@ jobs:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     permissions:
       contents: write
-    needs: [app-build]
     runs-on: ubuntu-latest
+    needs: [app-build]
 
     steps:
     - uses: actions/checkout@v4
@@ -76,8 +91,8 @@ jobs:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains( github.event.head_commit.message, 'release/' )
     permissions:
       contents: write
-    needs: [app-build]
     runs-on: ubuntu-latest
+    needs: [app-build, get-current-version]
 
     steps:
     - uses: actions/checkout@v4
@@ -85,14 +100,11 @@ jobs:
       uses: actions/download-artifact@v3
       with:
         name: app
-    - name: Get version
-      id: version
-      run: echo "version=$(python ${{ needs.app-build.outputs.app }} --version)" >> $GITHUB_OUTPUT
     - name: Create Release
       uses: softprops/action-gh-release@v1
       with:
-        name: v${{ steps.version.outputs.version }}
-        tag_name: v${{ steps.version.outputs.version }}
+        name: v${{ needs.get-current-version.outputs.version }}
+        tag_name: v${{ needs.get-current-version.outputs.version }}
         draft: false
         prerelease: false
         token: ${{ secrets.GITHUB_TOKEN }}
